### PR TITLE
CMake: improvements (honor compiler flags, add several options, fix install and export targets)

### PR DESCRIPTION
**Pull request by SpaceIm**
This PR improves CMake build of flecs:

- add options to build static or shared or both (I would have loved preventing to build both static and shared -because it forces to use 2 different imported targets for shared and static- but since it's already there I can't remove this feature without eventually breaking several downstream projects)
- add an option to enable full warnings
- add an option to disable PIC on non Windows plarforms
- honor `CMAKE_*_FLAGS*` from user
- rely on `C_VISIBILITY_PRESET` property instead of -fvisibility=hidden
- remove invalid warnings options for C
- export targets in `flecs-config.cmake` to be able to consume flecs with `find_package(flecs)`, then `target_link_libraries(myapp flecs::flecs)` or `target_link_libraries(myapp flecs::flecs_static)`. These namespaced targets also work with `add_subdirectory()`.

closes https://github.com/SanderMertens/flecs/issues/319

### CODE REVIEW

**Review by rawbby — APPROVED** [review]
@SpaceIm That is my fault :/
Copied some of the CMake code from a project of mine where I wanted specific compiler flags to be set. Some CMakes predefined flags where incompatible with mine so I decided to explicitly (un)set them.
Now I see why this is not a good idea.

**Review by rawbby — APPROVED** [review]

**Comment by SanderMertens** [comment]
Oops, just realized that you pushed fixes after I merged master into the branch @SpaceIm. Feel free to reopen the issue / create a new PR if there were more things you'd like to add.

**Comment by SpaceIm** [comment]
@SanderMertens LGTM, the last commit since to be in master ;)

**Comment by SanderMertens** [comment]
Great, thanks for the PR! @rawbby thanks for reviewing :)

**Pull request merged**
