### PR TITLE
Add support for building the tests with CMake

### PR DESCRIPTION
**Pull request by Naios**
Requires a present bake repository in test/ or in a path set via BAKE_REPOSITORY

You can then also add CTest to the github workflow:

```
cmake -DFLECS_TESTS=ON -DBAKE_REPOSITORY="${PATH_TO_BAKE_REPOSITORY}" .......

ctest -C Debug --verbose
```

Runs the tests single-threaded in MSVC

Ref https://github.com/SanderMertens/flecs/pull/1036

### CODE REVIEW

**Comment by SanderMertens** [comment]
I just tried this out locally, am getting the following error:
```
~/GitHub/SanderMertens/flecs$ cmake -DFLECS_TESTS=ON -DBAKE_REPOSITORY=~/GitHub/SanderMertens/bake
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at test/CMakeLists.txt:8 (message):
  The CMake tests require a bake repository at
  '/Users/sandermertens/GitHub/SanderMertens/flecs/test/bake'.
```

Looks like it's ignoring the argument:
```
The CMake tests require a bake repository at
'/Users/sandermertens/GitHub/SanderMertens/flecs/test/bake'
```

**Comment by SanderMertens** [comment]
Ah, it should be `BAKE_DIRECTORY`

**Comment by SanderMertens** [comment]
Can you add this to the end of `.github/workflows/ci.yml`?

```yml
test-cmake:
    needs: [ build-linux ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: clone bake
        run: |
          git clone https://github.com/SanderMertens/bake

      - name: build flecs & tests
        run: |
          cmake -DFLECS_TESTS=ON -DBAKE_DIRECTORY=bake
          make -j 8

      - name: run tests
        run: |
          ctest -C Debug --verbose
```

**Comment by Naios** [comment]
I have updated it accordingly. But I dont have time currently, to fix any resulting build failures.
Maybe it would be a good start to allow the build to fail and keep the support experimental.

**Comment by SanderMertens** [comment]
I couldn't push to this PR, so I branched off and created a new one to add the CI tests. Thanks for the PR!

**Comment by Naios** [comment]
Thank you for merging.

**Pull request closed without merging**
